### ISSUE TITLE
ParseIntError when running rbspy-armv7 in an arm container, x86 host using qemu-arm-static

### ISSUE THREAD

**Issue by doudou** [rbspy/proc-maps#15]
buildbot@99a65ee597a5:/buildbot$ ./rbspy-armv7-musleabihf snapshot --pid 8614
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-maps-0.1.8/src/linux_maps.rs:66:65

The one thing that is maybe out of place is the fact that I use qemu-arm-static to run the ruby binary (ARM container running on a x86 host). The maps of the process looks like this [maps.txt](https://github.com/rbspy/proc-maps/files/7435997/maps.txt), the first few lines look out of place (I'm guessing this might be the issue, maybe ?)

**Comment by acj** [comment]
Thanks for the report. Given...

> rbspy-armv7-musleabihf

and

> ParseIntError { kind: PosOverflow }

... I think we're trying to load a 64-bit memory address into a 32-bit integer. proc-maps is able to parse your maps.txt file on my (64-bit) machine. I'm not familiar with qemu internals -- maybe there's a mix of host and container memory that's causing the mismatch.

Are you running rbspy in the same container as the program you're profiling?

**Comment by doudou** [comment]
> Are you running rbspy in the same container as the program you're profiling?

Yes. But I'm running a armv7 container on a x86-64 host using the qemu-arm-static interpreter. Tbh, I think it would be fair to close this as "just unsupported.".

Turns out that this setup does not support ptrace anyways ... so no rbspy in the first place.
